# STAGE 1 
FROM node:16.17.0 AS install
WORKDIR /home/node/app
COPY package.json .
RUN npm install

# STAGE 2
FROM node:16.17.0
WORKDIR /home/node/app
COPY --from=install /home/node/app/node_modules ./node_modules
COPY package.json .
COPY package-lock.json .
COPY config .
COPY controllers .
COPY models .
COPY routes .
COPY utils .
COPY index.js .
COPY ./variables.env ./variables.env
EXPOSE 3000
